CC=qcc
CFLAGS=-Wall
LDFLAGS=-lsocket
TARGET=-Vgcc_ntoaarch64le
SRC_DIR=src
all: server client
server: $(SRC_DIR)/server.c
	$(CC) $(TARGET) $(CFLAGS) $(SRC_DIR)/server.c -o server $(LDFLAGS)
client: $(SRC_DIR)/client.c
	$(CC) $(TARGET) $(CFLAGS) $(SRC_DIR)/client.c -o client $(LDFLAGS)
clean:
	rm -f server client
